services:
  - type: web
    name: quizbot-backend
    env: java
    rootDir: backend
    buildCommand: ./gradlew build
    startCommand: ./gradlew bootRun
    envVars:
      - key: JAVA_VERSION
        value: 17
